export type Locale = 'es' | 'pt' | 'en';
export const languages = [{value:'es',label:'Español'},{value:'pt',label:'Português'},{value:'en',label:'English'}];
export const copy = {
es: {lang:'es-CL',title:'La Mesa Redonda | Hamburguesería en Santiago',nav:'Navegación principal',home:'Inicio',menu:'Menú',where:'Dónde estamos',order:'Pedir en línea',eyebrow:'HAMBURGUESERÍA · SANTIAGO, CHILE',hero:['BUENOS MOMENTOS.','UNA MESA.','MUCHO SABOR.'],intro:['Tu próximo encuentro tiene dirección.','Siéntate a la mesa. El resto es sabor.'],myOrder:'HACER MI PEDIDO',explore:'Explorar menú',experience:'LA EXPERIENCIA COMIENZA AQUÍ',illustration:'Imagen ilustrativa',ticker:'EL SABOR DEL ENCUENTRO',visit:'02 / NOS ENCONTRAMOS AQUÍ',seat:['TU LUGAR','EN LA MESA.'],route:'Cómo llegar',come:'VEN A VISITARNOS',opening:'HORA DE APERTURA INFORMADA',hours:'Consulta los días y horarios por teléfono.',contact:'HABLA CON NOSOTROS',footer:'Hamburguesas. Encuentros. Santiago.',rappi:'Pide por Rappi',choose:'01 / ELIGE TU FAVORITO',menuTitle:['UN MENÚ.','MUCHAS LEYENDAS.'],toast:'Del primer bocado al último brindis.',currency:'Precios en pesos chilenos (CLP)',original:'Ver menú original',categories:'Categorías del menú',options:'OPCIONES',vegan:'VEGANA',promo:'En el menú original: 2 schops por $3.000 hasta las 16:00. Consulta las condiciones y la disponibilidad en el local.',notice:['Productos y precios según el menú proporcionado.','Confirma la disponibilidad al hacer tu pedido.'],rappiButton:'PEDIR POR RAPPI',skip:'Ir al contenido',language:'Elegir idioma'},
pt: {lang:'pt-BR',title:'La Mesa Redonda | Hamburgueria em Santiago',nav:'Navegação principal',home:'Início',menu:'Cardápio',where:'Onde estamos',order:'Pedir on-line',eyebrow:'HAMBURGUERIA · SANTIAGO, CHILE',hero:['BONS MOMENTOS.','UMA MESA.','MUITO SABOR.'],intro:['O próximo encontro tem endereço.','Sente-se à mesa. O resto é sabor.'],myOrder:'FAZER MEU PEDIDO',explore:'Explorar cardápio',experience:'A EXPERIÊNCIA COMEÇA AQUI',illustration:'Imagem ilustrativa',ticker:'O SABOR DO ENCONTRO',visit:'02 / NOS ENCONTRAMOS AQUI',seat:['SEU LUGAR','À MESA.'],route:'Traçar minha rota',come:'VENHA NOS VISITAR',opening:'ABERTURA INFORMADA',hours:'Consulte os dias e horários por telefone.',contact:'FALE COM A MESA',footer:'Hambúrgueres. Encontros. Santiago.',rappi:'Peça pelo Rappi',choose:'01 / ESCOLHA O SEU FAVORITO',menuTitle:['UM CARDÁPIO.','MUITAS LENDAS.'],toast:'Da primeira mordida ao último brinde.',currency:'Preços em pesos chilenos (CLP)',original:'Ver cardápio original',categories:'Categorias do cardápio',options:'OPÇÕES',vegan:'VEGANA',promo:'No cardápio original: 2 schops por $3.000 até as 16h. Consulte as condições e a disponibilidade no local.',notice:['Produtos e preços conforme o cardápio fornecido.','Confirme a disponibilidade ao fazer seu pedido.'],rappiButton:'PEDIR PELO RAPPI',skip:'Ir para o conteúdo',language:'Escolher idioma'},
en: {lang:'en',title:'La Mesa Redonda | Burgers in Santiago',nav:'Main navigation',home:'Home',menu:'Menu',where:'Find us',order:'Order online',eyebrow:'BURGER RESTAURANT · SANTIAGO, CHILE',hero:['GOOD TIMES.','ONE TABLE.','GREAT FLAVOR.'],intro:['Your next gathering has an address.','Take a seat. Let flavor do the rest.'],myOrder:'PLACE MY ORDER',explore:'Explore the menu',experience:'THE EXPERIENCE STARTS HERE',illustration:'Illustrative image',ticker:'THE TASTE OF GOOD COMPANY',visit:'02 / MEET US HERE',seat:['YOUR PLACE','AT THE TABLE.'],route:'Get directions',come:'COME VISIT US',opening:'LISTED OPENING TIME',hours:'Call to confirm opening days and hours.',contact:'GET IN TOUCH',footer:'Burgers. Gatherings. Santiago.',rappi:'Order on Rappi',choose:'01 / PICK YOUR FAVORITE',menuTitle:['ONE MENU.','MANY LEGENDS.'],toast:'From the first bite to the last toast.',currency:'Prices in Chilean pesos (CLP)',original:'View original menu',categories:'Menu categories',options:'OPTIONS',vegan:'VEGAN',promo:'In the original menu: 2 draft beers for $3,000 until 4 pm. Check terms and availability at the restaurant.',notice:['Products and prices from the supplied menu.','Confirm availability when ordering.'],rappiButton:'ORDER ON RAPPI',skip:'Skip to content',language:'Choose language'}
};
const labels: Record<string,[string,string,string]> = {
'Smash burgers':['Smash burgers','Smash burgers','Smash burgers'], 'Para acompanhar':['Para acompañar','Para acompanhar','Sides'], 'Bebidas e cervejas':['Bebidas y cervezas','Bebidas e cervejas','Drinks & beers'], 'Coquetéis e peceras':['Cócteles y peceras','Coquetéis e peceras','Cocktails & fishbowls'],
'As estrelas da mesa':['Las estrellas de la mesa','As estrelas da mesa','Stars of the table'], 'Extras para seu hambúrguer':['Extras para tu hamburguesa','Extras para seu hambúrguer','Burger extras'], 'Acompañamientos':['Acompañamientos','Acompanhamentos','Sides'], 'Nachos':['Nachos','Nachos','Nachos'], 'Papas legendarias':['Papas legendarias','Batatas lendárias','Legendary fries'], 'Sem álcool':['Sin alcohol','Sem álcool','Alcohol-free'], 'Schop · 600 ml':['Schop · 600 ml','Chope · 600 ml','Draft beer · 600 ml'], 'Botella litro':['Botella litro','Garrafas de litro','Liter bottles'], 'Cervejas em garrafa':['Cervezas en botella','Cervejas em garrafa','Bottled beers'], 'Complemente sua cerveja':['Acompaña tu cerveza','Complemente sua cerveja','Beer extras'], 'Coctelería':['Coctelería','Coquetéis','Cocktails'], 'Peceras':['Peceras','Peceras (drinks para compartilhar)','Fishbowl cocktails'],
'Carne + Cheddar':['Carne + Cheddar','Carne + Cheddar','Beef + Cheddar'], 'Champiñones':['Champiñones','Cogumelos','Mushrooms'], 'Cebolla Caramelizada':['Cebolla Caramelizada','Cebola caramelizada','Caramelized onion'], 'Agua':['Agua','Água','Water'], 'Bebidas':['Bebidas','Refrigerantes','Soft drinks'], 'Limonadas':['Limonadas','Limonadas','Lemonades'], 'Jugos':['Jugos','Sucos','Juices'], 'Aros de Cebolla':['Aros de Cebolla','Anéis de cebola','Onion rings']
};
export function menuLabel(text:string, locale:Locale) { return labels[text]?.[{es:0,pt:1,en:2}[locale]] ?? text; }
