export type MenuItem = { name: string; price: number; description?: string; image?: string };
export type MenuGroup = { title: string; items: MenuItem[] };
const item = (name: string, price: number, description = '', image?: string): MenuItem => ({name, price, description, image});
export const menuCategories: {id: string; label: string; groups: MenuGroup[]}[] = [
{id:'burgers',label:'Smash burgers',groups:[{title:'As estrelas da mesa',items:[
item('La Excalibur',9900,'Triple carne smash de 110 g, cheddar, queso mantecoso, fondue de queso azul, cebolla crispy, tocino ahumado y salsa del rey.','2-6'),
item('Rey Arturo',8900,'Doble carne smash de 110 g, doble fondue de queso azul, rúcula, champiñones salteados, mermelada de tocino y salsa mil islas.','2-2'),
item('Blue Cheese Caramel',8900,'Doble carne smash de 110 g, doble fondue de queso azul, rúcula, cebolla caramelizada, tocino ahumado, pepinillos de la casa y salsa aioli.','2-7'),
item('La Chilindrina',8500,'Doble carne smash de 110 g, doble cheddar, guacamole, mermelada de jalapeño, nachos y salsa mil islas.','2-3'),
item('Oklahoma',7700,'Doble carne smash de 110 g, doble cheddar, cebolla grill smasheada en carne, tocino ahumado, pepinillos de la casa y salsa del rey.','2-4'),
item('Lancelot Jalapeño',7700,'Doble carne smash de 110 g, doble cheddar, jalapeños en rodajas, cebolla crispy, tocino ahumado y salsa aioli.','2-5'),
item('Doble Cheeseburger',5900,'Doble carne smash de 110 g, doble cheddar americano, pepinillos, cebolla crispy y salsa del rey.','3-3'),
item('Doble 1/4 de Libra',6900,'Doble carne smash de 110 g, doble cheddar, cebolla morada brumada, pepinillos, salsa del rey, ketchup y mostaza.','3-4'),
item('BLT',7700,'Doble carne smash de 110 g, doble queso mantecoso, tocino ahumado, lechuga hidropónica, tomate, pepinillos de la casa y salsa mil islas.','3-2'),
item('Texana',7900,'Doble carne smash de 110 g, doble cheddar, aros de cebolla, pepinillos de la casa, mermelada de tocino y salsa del rey.','3-6'),
item('Merlin (Fungi Onion)',7900,'Doble carne smash de 110 g, doble queso mantecoso, tocino ahumado, cebolla caramelizada, champiñones salteados y salsa mil islas.','3-5'),
item('Vegana',7500,'Hamburguesa vegana, tomate, lechuga, champiñones, cebolla caramelizada y Not Mayo.','3-7')
]},{title:'Extras para seu hambúrguer',items:[item('Carne + Cheddar',2000),item('Cheddar',1000),item('Bacon',1000),item('Champiñones',1000),item('Cebolla Caramelizada',1000)]}]},
{id:'sides',label:'Para acompanhar',groups:[{title:'Acompañamientos',items:[item('Aros de Cebolla',5000,'Clásicos aros de cebolla, crujientes y deliciosos.'),item('Chicken Tenders',5000,'Tiras de pollo empanadas con salsa aioli o BBQ.'),item('Mozzarella Sticks',5000,'Dedos de mozzarella empanados con salsa tártara.')]},{title:'Nachos',items:[item('Nachos Mechados',7500,'Nachos con guacamole fresco, queso cheddar y carne mechada de la casa.'),item('Nachos Bacon',6000,'Nachos con guacamole cremoso, cheddar derretido y bacon ahumado.'),item('Nachos Clásicos',6000,'Nachos con guacamole cremoso, cheddar derretido y jalapeños.')]},{title:'Papas legendarias',items:[item('Chorrillana Clásica',9000,'Papas crujientes con proteína, longaniza, cebolla caramelizada y un huevo frito.'),item('Papachas Mechadas',7500,'Papas crujientes con cheddar derretido y carne mechada de la casa.'),item('Papas Cheddar Tocino',6500,'Papas crujientes con tocino crispy y queso cheddar derretido.')]}]},
{id:'drinks',label:'Bebidas e cervejas',groups:[{title:'Sem álcool',items:[item('Agua',1000),item('Bebidas',1500),item('Limonadas',1500),item('Jugos',3000)]},{title:'Schop · 600 ml',items:[item('Austral Calafate',4500,'Cerveza patagónica con baya de calafate. Ámbar oscuro y equilibrio dulce-amargo.'),item('Heineken',2500,'Lager pálida, refrescante y equilibrada.'),item('Cristal',2000,'Lager chilena ligera, con notas de malta y lúpulo.')]},{title:'Botella litro',items:[item('Heineken',4500),item('Royal',4500),item('Volcanes del Sur',4000),item('Budweiser',3500),item('Cristal · 1,2 L',3500),item('Escudo · 1,2 L',3500)]},{title:'Cervejas em garrafa',items:[item('Torobayo',3900),item('Dolbek Maqui',3900),item('Kross · 330 cc',3500),item('Kunstmann Miel',3900),item('Austral Torres del Paine',3900),item('Valdivia',3900),item('Budweiser · 660 cc',2700),item('Stella Artois · 660 cc',2500),item('Corona · 710 cc',2700),item('Royal · 660 cc',2500),item('Mistral Ice · 330 cc',2500)]},{title:'Complemente sua cerveja',items:[item('Chelada',1000,'Adicional'),item('Michelada',2000,'Adicional')]}]},
{id:'cocktails',label:'Coquetéis e peceras',groups:[{title:'Coctelería',items:[
item('Sangría Jarra',9000,'Vino tinto, frutas picadas y licor de naranja.'),item('Sangría Copa',5000,'Vino tinto, frutas picadas y licor de naranja.'),item('Gin Tonic',5000,'Ginebra y agua tónica.'),item('Gin Sabores',5000,'Ginebra, agua tónica y frutas o especias.'),item('Pisco Sour',3500,'Pisco, jugo de limón y azúcar.'),item('Pisco Catedral',5500,'Pisco, jugo de limón y azúcar. Ingredientes adicionales pueden variar.'),item('Tequila Margarita',5500,'Tequila, licor de naranja y jugo de limón.'),item('Piscola',5000,'Pisco y refresco de cola.'),item('Aperol',5500,'Aperol, Prosecco y agua con gas.'),item('Mojito',5000,'Ron blanco, hierbabuena, azúcar, limón y agua con gas.'),item('Mojito Sabores',5500,'Ron blanco, hierbabuena, azúcar, limón, agua con gas y frutas o jarabes.'),item('Ramazzotti',6000,'Licor Ramazzotti.'),item('Negroni',5500,'Ginebra, vermut rojo y Campari.'),item('Daikiri Sabores',6000,'Ron blanco, limón, azúcar y frutas o jarabes.'),item('Cuba Libre (Ron Cola)',5000,'Ron blanco, refresco de cola y limón.'),item('Tom Collins',6000,'Ginebra, limón, azúcar y agua con gas.'),item('Old Fashion',5000,'Bourbon o Rye Whiskey, azúcar y amargo de Angostura.'),item('Sex on the Beach',6000,'Vodka, licor de durazno, jugo de arándano y jugo de naranja.'),item('Terremoto Jarra',9000,'Pipeño, helado de piña y granadina.'),item('Terremoto Copa',4000,'Pipeño, helado de piña y granadina.'),item('Tsunami Jarra',9000,'Pipeño, helado de piña y Curazao azul.'),item('Tsunami Copa',4000,'Pipeño, helado de piña y Curazao azul.'),item('Caipiroska',5000,'Vodka, azúcar y limón.'),item('Caipirinha',5000,'Cachaça, azúcar y limón.'),item('Piña Colada',5000,'Ron blanco, leche de coco y jugo de piña.')
]},{title:'Peceras',items:[item('Sombra del Rey',15000,'Sprite, Blue Curaçao y vodka negro.'),item('Brebaje Real',15000,'Ron de coco, vodka, blue curaçao, jugo de piña y limón.'),item('Camelot Rosa',15000,'Vodka o ron, jugo de piña, granadina y crema de leche.'),item('Corona Dorada',15000,'Tequila, limón, jugo de naranja y cerveza Corona.')]}]}
];
