'use client';
/* oxlint-disable next/no-img-element -- Local menu assets use fixed dimensions and lazy loading on both static and Sites builds. */
import { ArrowUpRight } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { menuCategories } from './menu-data';
const price = (value: number) => '$' + new Intl.NumberFormat('es-CL').format(value);
export default function RestaurantMenu() {
return <section className="restaurant-menu" id="cardapio" aria-labelledby="menu-heading"><div className="menu-heading-row"><div><p className="eyebrow muted">01 / ESCOLHA O SEU FAVORITO</p><h2 id="menu-heading">UM CARDÁPIO.<br/><span>MUITAS LENDAS.</span></h2></div><div className="menu-heading-note"><p>Da primeira mordida ao último brinde.</p><span>Preços em pesos chilenos (CLP)</span><a href="https://drive.google.com/file/d/1lS13PyfqNc4YmnU80ek9CKsBl0sNp5RG/view" target="_blank" rel="noreferrer">Ver cardápio original <ArrowUpRight size={16}/></a></div></div>
<Tabs defaultValue="burgers" className="food-tabs"><TabsList className="category-tabs" aria-label="Categorias do cardápio">{menuCategories.map(c=><TabsTrigger key={c.id} value={c.id} className="category-tab">{c.label}</TabsTrigger>)}</TabsList>{menuCategories.map(c=><TabsContent key={c.id} value={c.id} className="category-panel">{c.groups.map((group,gi)=><div className="menu-group" key={group.title}><div className="group-title"><span>{String(gi+1).padStart(2,'0')}</span><h3>{group.title}</h3><span>{group.items.length} OPÇÕES</span></div><div className={c.id==='burgers'&&gi===0?'burger-grid':'dishes-grid'}>{group.items.map(dish=><article key={dish.name} className={dish.image?'burger-card':'dish-row'}>{dish.image&&<div className="burger-photo"><img src={`/images/menu-${dish.image}.png`} alt={dish.name} loading="lazy" width={260} height={220}/>{dish.name==='Vegana'&&<span className="food-tag">VEGANA</span>}</div>}<div className="dish-info"><div className="dish-name"><h4>{dish.name}</h4><span>{price(dish.price)}</span></div>{dish.description&&<p lang="es">{dish.description}</p>}</div></article>)}</div></div>)}{c.id==='drinks'&&<p className="menu-promo">No cardápio original: 2 schops por $3.000 até as 16h. Consulte as condições e a disponibilidade no local.</p>}</TabsContent>)}</Tabs><div className="menu-end"><p>Produtos e preços conforme o cardápio fornecido.<br/>Confirme a disponibilidade ao fazer seu pedido.</p><a className="button primary" href="https://www.rappi.cl/santiago-de-chile/restaurantes/delivery/68328-la-mesa-redonda" target="_blank" rel="noreferrer">PEDIR PELO RAPPI <ArrowUpRight size={20}/></a></div></section>;
}


